### PR TITLE
kubevirt_vm_info: Add info module for VirtualMachines

### LINKED ISSUE #22: Add kubevirt_vm_info module
##### SUMMARY
To gather information about existing VMs an info module for `kubevirt_vm` should be added. See [1]. 

This module should only return information about an existing virtual machine without the possibility of changing it. The module's return values should resemble those of `kubevirt_vm`.

[1] https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#creating-an-info-or-a-facts-module

##### ISSUE TYPE
 - Feature Idea

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This adds the kubevirt_vm_info module, which returns the same results as
the kubevirt_vm module, but is limited to read-only functionality.

**Which issue(s) this PR fixes**:

Fixes #22

**Release note**:

```release-note
Add kubevirt_vm_info module to describe existing VirtualMachines
```

### CODE REVIEW

**Comment by jcanocan** [comment]
Nice job! Just one question, is the dependencies update strictly required? If not, IMHO they should be updated in a separate PR.

**Comment by 0xFelix** [comment]
@jcanocan Strictly speakong only the common-instancetypes update is required for the added integration test, but I would keep it as part of this PR.

**Pull request merged**
